#include "utilities.h"

enum TokenType {
  INVALID_TOKEN = CONSTANTS::TOKEN_ID_START,
  INTEGER,
  DOUBLE,
  STRING,
  COMMENT,
  RESERVED,
  IDENTIFIER,
  FUNCTION_CALL,
  TERM,
  EQUATION,
  EXPRESSION,
  ASSIGNMENT_STATEMENT,
  DATATYPE,
  DECLARATION_STATEMENT,
  WRITE_STATEMENT,
  READ_STATEMENT,
  RETURN_STATEMENT,
  CONDITIONAL_OPERATOR,
  CONDITION,
  BOOLEAN_OPERATOR,
  CONDITIONAL_STATEMENT,
  IF_STATEMENT,
  ELSE_IF_STATEMENT,
  ELSE_STATEMENT,
  REPEAT_STATEMENT,
  FUNCTION_NAME,
  PARAMETER,
  FUNCTION_DECLARATION,
  FUNCTION_BODY,
  FUNCTION_STATEMENT,
  MAIN_FUNCTION,
  PROGRAM,
  WHITESPACE,
  PARAN_OPEN,
  PARAN_CLOSE,
  OPERATOR_PLUS,
  OPERATOR_MINUS,
  OPERATOR_TIMES,
  OPERATOR_ASSIGNMENT,
  QUOTE_OPEN,
  QUOTE_CLOSE,
  END_OF_FILE
};

struct Token {
  TokenType token_type;
  std::string lexeme;
  static std::string token_name(TokenType token) {
    return CONSTANTS::TOKEN_NAMES[token - CONSTANTS::TOKEN_ID_START];
  }
  Token() {
    token_type = TokenType::INVALID_TOKEN;
    lexeme = "";
  }
};
